let data = [
  {
    _id: "1",
    name: "Dress 1",
    slug: "Dress1",
    img: "/images/1.jpg",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vel molestie turpis. Morbi at purus scelerisque, lobortis turpis ac, maximus dolor.",
    price: "400",
    ratings: "5",
    numberOfRatings: "120",
    stock: 3,
    category: "women",
    coupon: "abc",
    discount: 20,
    totalSales: 100,
  },
  {
    _id: "2",
    name: "Dress 2",
    slug: "Dress2",
    img: "/images/2.jpg",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vel molestie turpis. Morbi at purus scelerisque, lobortis turpis ac, maximus dolor.",
    price: "600",
    ratings: "3.5",
    numberOfRatings: "130",
    stock: 2,
    category: "men",
    coupon: "abcd",
    discount: 25,
    totalSales: 200,
  },
  {
    _id: "3",
    name: "Dress 3",
    slug: "Dress3",
    img: "/images/3.jpg",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vel molestie turpis. Morbi at purus scelerisque, lobortis turpis ac, maximus dolor.",
    price: "800",
    ratings: "4",
    numberOfRatings: "140",
    stock: 0,
    category: "women",
    coupon: "abcde",
    discount: 10,
    totalSales: 30,
  },
  {
    _id: "4",
    name: "Dress 4",
    slug: "Dress4",
    img: "/images/4.jpg",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vel molestie turpis. Morbi at purus scelerisque, lobortis turpis ac, maximus dolor.",
    price: "900",
    ratings: "4.5",
    numberOfRatings: "100",
    stock: 2,
    category: "men",
    coupon: "abcdef",
    discount: 40,
    totalSales: 300,
  },

  {
    _id: "5",
    name: "Dress 5",
    slug: "Dress5",
    img: "/images/2.jpg",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vel molestie turpis. Morbi at purus scelerisque, lobortis turpis ac, maximus dolor.",
    price: "400",
    ratings: "5",
    numberOfRatings: "120",
    stock: 10,
    category: "men",
    coupon: "",
    discount: 0,
    totalSales: 50,
  },

  {
    _id: "6",
    name: "Dress 6",
    slug: "Dress6",
    img: "/images/1.jpg",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vel molestie turpis. Morbi at purus scelerisque, lobortis turpis ac, maximus dolor.",
    price: "400",
    ratings: "5",
    numberOfRatings: "120",
    stock: 10,
    category: "men",
    coupon: "",
    discount: 0,
    totalSales: 50,
  },
  {
    _id: "7",
    name: "Dress 7",
    slug: "Dress 7",
    img: "/images/child1.jpg",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vel molestie turpis. Morbi at purus scelerisque, lobortis turpis ac, maximus dolor.",
    price: "400",
    ratings: "5",
    numberOfRatings: "120",
    stock: 10,
    category: "children",
    coupon: "",
    discount: 0,
    totalSales: 50,
  },
  {
    _id: "8",
    name: "Dress 8",
    slug: "Dress 8",
    img: "/images/child2.jpg",
    description:
      "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam vel molestie turpis. Morbi at purus scelerisque, lobortis turpis ac, maximus dolor.",
    price: "400",
    ratings: "5",
    numberOfRatings: "120",
    stock: 10,
    category: "children",
    coupon: "",
    discount: 0,
    totalSales: 50,
  },
];

module.exports = data;
